services:
  postgres:
    image: postgres:17-alpine
    container_name: supplyflow-postgres
    environment:
      POSTGRES_DB: supplyflow
      POSTGRES_USER: supplyflow
      POSTGRES_PASSWORD: supplyflow
    ports:
      - "5433:5432"
    volumes:
      - supplyflow-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.3-management
    container_name: supplyflow-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: supplyflow
      RABBITMQ_DEFAULT_PASS: supplyflow
    ports:
      - "5672:5672"
      - "15672:15672"
      
  postgres-supplier:
    image: postgres:17-alpine
    container_name: supplyflow-postgres-supplier
    environment:
      POSTGRES_DB: supplyflow_supplier
      POSTGRES_USER: supplyflow
      POSTGRES_PASSWORD: supplyflow
    ports:
      - "5434:5432"
    volumes:
      - supplyflow-postgres-supplier-data:/var/lib/postgresql/data
      
  redis:
    image: redis:8.2.9-alpine
    container_name: supplyflow-redis
    ports:
      - "6379:6379"
      
  jaeger:
    image: jaegertracing/jaeger:2.21.0
    container_name: supplyflow-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: supplyflow-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:13.0.9
    container_name: supplyflow-grafana
    ports:
      - "3000:3000"
      
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.4
    container_name: supplyflow-keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  supplyflow-postgres-data:
  supplyflow-postgres-supplier-data: