<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SupplyFlow.Supplier.Application\SupplyFlow.Supplier.Application.csproj" />
    <ProjectReference Include="..\SupplyFlow.Supplier.Domain\SupplyFlow.Supplier.Domain.csproj" />
    <ProjectReference Include="..\SupplyFlow.Contracts\SupplyFlow.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.9" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
