<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SupplyFlow.Procurement.Application\SupplyFlow.Procurement.Application.csproj" />
    <ProjectReference Include="..\SupplyFlow.Procurement.Infrastructure\SupplyFlow.Procurement.Infrastructure.csproj" />
    <ProjectReference Include="..\SupplyFlow.Contracts\SupplyFlow.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
