<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SupplyFlow.Supplier.Application\SupplyFlow.Supplier.Application.csproj" />
    <ProjectReference Include="..\SupplyFlow.Supplier.Infrastructure\SupplyFlow.Supplier.Infrastructure.csproj" />
    <ProjectReference Include="..\SupplyFlow.Contracts\SupplyFlow.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
